on: 
  push:
    branches:
      - main 
      - test 

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      update: ${{steps.update_step.outputs.update}}

    steps:
    - uses: actions/checkout@v2

    - id: update_step
      shell: pwsh
      name: Check for updates
      run: | 
        $reposWithUpdates = (.\updater.ps1 -orgName ${{ github.repository_owner }} -userName "xxx" -PAT ${{ secrets.GITHUB_TOKEN }} -issuesRepository ${{ github.repository }} )[-1]
        Write-Host "Are there any updates available? [$($reposWithUpdates.Count -gt 0)]"
        echo "::set-output name=update::$($reposWithUpdates.Count -gt 0)"