name: Run Pester Tests

on:
  pull_request:
    branches: [ main ]

  push:
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . -f .devcontainer/Dockerfile -t unittest-image

    - name: Run Pester tests in the container
      run: |
        docker run --name unittest-container -d unittest-image
        docker exec unittest-container pwsh -Command "Invoke-Pester"