name: Run Pester Tests

on:
  pull_request:
    branches: [ main ]

  push:
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . -f .devcontainer/Dockerfile -t unittest-image

    - name: Run Pester tests in the container
      run: |
        # run the container with the source code mounted as a volume
        docker run --name unittest-container -v ${{ github.workspace }}:/workspace -d unittest-image
        
        echo "Running the tests"	
        docker exec unittest-container pwsh -Command {
          try {
            Invoke-Pester
          } catch {
            Write-Host "Error: $_"
            exit 1
          }
        }