on: 
  issues:
    types: [labeled]

jobs:
  update-fork:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'update-fork'

    steps:
    - uses: actions/checkout@v2

    - run: echo "hello world"
    - run: echo "${{ github.event.issue.id }}"