on: 
  issues:
    types: [labeled]

jobs:
  update-fork:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'update-fork'

    steps:
    - uses: asml-actions/workflow-application-token-action@main
      id: get_workflow_token
      with:
        application_id: ${{ secrets.GH_AUTOMATION_ID }}
        application_private_key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY }}

    - uses: actions/checkout@v2

    - run: |
       echo "Found the issue that triggered this event with number [${{ github.event.issue.number }}]"
       echo "Found the issue title [${{ github.event.issue.title }}]"

    - run: |
       .\update-fork.ps1 -orgName ${{ github.repository_owner }} -userName "xxx" -PAT ${{ steps.get_workflow_token.outputs.token }} -issueTitle "${{ github.event.issue.title }}" -issueId ${{ github.event.issue.number }} -issuesRepository  ${{ github.repository }}
      shell: pwsh