on: 
  push:
    branches:
      - main  

jobs:
  check-for-updates:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: $updatesAvailable = pwsh updater.ps1
    - id: update_step
      run: echo "::set-output name=updatesAvailable::$updatesAvailable"

  run-update:
    runs-on: ubuntu-latest
    needs: check-for-updates
    steps:
    - run: echo 'hello world'
    - run: echo "${{ jobs.check-for-updates.steps.update_step.outputs.updatesAvailable }}"
